services:
  - type: web
    name: rtmodt
    env: python
    buildCommand: pip install -r requirements.txt && python tools/download_samples.py
    startCommand: uvicorn web.server:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: PORT
        value: 10000
